trigger:
- master

pool: 
  vmImage: windows-latest

steps:
- task: replacetokens@3
  displayName: Replace Variables
  inputs:
    targetFiles: '**/appsettings.config'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTelemetry: true

- task: DotNetCoreCLI@2
  displayName: Publish Agent for Windows x64
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'DogusTeknoloji.SmartKPIMiner.Agent.csproj'
    arguments: '-c Release -r win-x64'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'SmartKPI-Agent'
    publishLocation: 'Container'