trigger:
- master

pool: 'WindowsPool'

variables:
  solution: '**/DogusTeknoloji.SmartKPIMiner.Agent.csproj'
  testSolution: '**/DogusTeknoloji.SmartKPIMiner.Tests.csproj'
  runtime: 'win-x64'
  configuration: 'Release'

steps:
- task: replacetokens@3
  displayName: 'Replace Variables'
  inputs:
    targetFiles: '**/appsettings.json'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTelemetry: true

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build Smart KPI Miner'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-c $(configuration) -r $(runtime)'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '$(testSolution)'
    testRunTitle: 'Generic Unit Tests'

- task: DotNetCoreCLI@2
  displayName: 'Take release for Windows x64'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(solution)'
    arguments: '-c $(configuration) -r $(runtime) -o $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'SmartKPI-Agent'
    publishLocation: 'Container'